<a href="https://colab.research.google.com/github/sindhutej-6/dl_programs/blob/main/perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Sample data (AND gate)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])

In [ ]:
# Initialize weights and bias
weights = np.array([0.0, 0.0])
bias = 0

In [ ]:
# One iteration of Perceptron
for i in range(len(X)):
    x1, x2 = X[i]
    target = y[i]

    # Compute z = w.x + b
    z = weights[0] * x1 + weights[1] * x2 + bias

    # Activation function
    output = 1 if z >= 0 else 0

    # Update rule without learning rate or error term
    if output != target:
        if target == 1:
            # Add input to weights and increment bias
            weights[0] += x1
            weights[1] += x2
            bias += 1
        else:
            # Subtract input from weights and decrement bias
            weights[0] -= x1
            weights[1] -= x2
            bias -= 1

In [ ]:
# Final result
print("Weights after one iteration:", weights)
print("Bias after one iteration:", bias)

Weights after one iteration: [1. 1.]
Bias after one iteration: 0


## **Perceptron Convergence**

In [ ]:
import numpy as np

# Input data (AND gate)
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

# Target output
y = np.array([0, 0, 0, 1])

# Initialize weights and bias
weights = np.array([0, 0])
bias = 0

In [ ]:
# Training loop
epochs = 0

while True:
    error_count = 0  # Track number of misclassifications in an epoch

    for i in range(len(X)):
        x1, x2 = X[i]
        target = y[i]

        # Compute net input
        z = weights[0] * x1 + weights[1] * x2 + bias

        # Activation function (step function)
        output = 1 if z >= 0 else 0

        # Update rule (only if prediction is wrong)
        if output != target:
            error_count += 1
            if target == 1:
                weights[0] += x1
                weights[1] += x2
                bias += 1
            else:
                weights[0] -= x1
                weights[1] -= x2
                bias -= 1

    epochs += 1
    # Stop if no errors in this epoch
    if error_count == 0:
        break

In [ ]:
# Final result
print("Training complete in", epochs, "epochs")
print("Final weights:", weights)
print("Final bias:", bias)

# Test the trained model
print("\nTesting on all inputs:")
for i in range(len(X)):
    x1, x2 = X[i]
    z = weights[0] * x1 + weights[1] * x2 + bias
    output = 1 if z >= 0 else 0
    print(f"Input: {X[i]} → Output: {output}")

Training complete in 6 epochs
Final weights: [2 1]
Final bias: -3

Testing on all inputs:
Input: [0 0] → Output: 0
Input: [0 1] → Output: 0
Input: [1 0] → Output: 0
Input: [1 1] → Output: 1


# **Perceptron Model using Tensorflow**

In [ ]:
import tensorflow as tf

# Input data (AND gate)
X = tf.constant([[0, 0],
                 [0, 1],
                 [1, 0],
                 [1, 1]], dtype=tf.float32)

# Target output
y = tf.constant([0, 0, 0, 1], dtype=tf.float32)

In [ ]:
# Initialize weights and bias as TensorFlow variables
weights = tf.Variable([0.0, 0.0], dtype=tf.float32)
bias = tf.Variable(0.0, dtype=tf.float32)

In [ ]:
# Define activation function (step function)
def activation(z):
    return tf.where(z >= 0, 1.0, 0.0)

In [ ]:
# Training loop
epochs = 0
while True:
    error_count = 0
    for i in range(4):
        xi = X[i]
        target = y[i]

        # Compute z = w.x + b
        z = tf.reduce_sum(weights * xi) + bias

        # Step activation
        output = activation(z)

        # Check prediction
        if output != target:
            error_count += 1
            # Update weights and bias using perceptron rule
            if target == 1.0:
                weights.assign_add(xi)
                bias.assign_add(1.0)
            else:
                weights.assign_sub(xi)
                bias.assign_sub(1.0)

    epochs += 1
    if error_count == 0:
        break

In [ ]:
# Final weights and bias
print(f"Training complete in {epochs} epochs")
print("Final weights:", weights.numpy())
print("Final bias:", bias.numpy())

# Test on all inputs
print("\nTesting on all inputs:")
for i in range(4):
    xi = X[i]
    z = tf.reduce_sum(weights * xi) + bias
    output = activation(z)
    print(f"Input: {xi.numpy()} → Output: {int(output.numpy())}")

Training complete in 6 epochs
Final weights: [2. 1.]
Final bias: -3.0

Testing on all inputs:
Input: [0. 0.] → Output: 0
Input: [0. 1.] → Output: 0
Input: [1. 0.] → Output: 0
Input: [1. 1.] → Output: 1


**XOR using MLP**

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# 1. Define XOR data
# Input: [0,0], [0,1], [1,0], [1,1]
# Output: 0, 1, 1, 0
X = tf.constant([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=tf.float32)
y = tf.constant([[0], [1], [1], [0]], dtype=tf.float32)

print("X (Input):")
print(X)
print("\ny (Output):")
print(y)

X (Input):
tf.Tensor(
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]], shape=(4, 2), dtype=float32)

y (Output):
tf.Tensor(
[[0.]
 [1.]
 [1.]
 [0.]], shape=(4, 1), dtype=float32)


In [ ]:
# 2. Build the MLP model
# A simple MLP for XOR typically needs at least one hidden layer.
# We'll use a hidden layer with 2 neurons and a ReLU activation,
# and an output layer with 1 neuron and a Sigmoid activation.
model = Sequential([
    # Hidden layer
    Dense(units=2, activation='relu', input_shape=(2,)), # 2 neurons, ReLU activation, input shape is 2 features
    # Output layer
    Dense(units=1, activation='sigmoid') # 1 neuron for binary output, Sigmoid activation
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
# 3. Compile the model
# Optimizer: 'adam' is a good general-purpose optimizer.
# Loss function: 'binary_crossentropy' is suitable for binary classification.
# Metrics: 'accuracy' to monitor performance.
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Display model summary
print("\nModel Summary:")
model.summary()


Model Summary:


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# 4. Train the model
# We'll train for a sufficient number of epochs to allow the model to learn the XOR pattern.
print("\nTraining the model...")
history = model.fit(X, y, epochs=1000, verbose=0) # verbose=0 to suppress epoch-by-epoch output

print("Training finished.")

# Evaluate the model
loss, accuracy = model.evaluate(X, y, verbose=0)
print(f"\nModel Evaluation:")
print(f"Loss: {loss:.4f}")
print(f"Accuracy: {accuracy:.4f}")

# Make predictions
print("\nPredictions on XOR inputs:")
predictions = model.predict(X)
for i in range(len(X)):
    print(f"Input: {X[i]}, Expected Output: {y[i][0]}, Predicted Output: {predictions[i][0]:.4f} (Rounded: {round(predictions[i][0])})")



Training the model...
Training finished.

Model Evaluation:
Loss: 0.5545
Accuracy: 0.7500

Predictions on XOR inputs:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
Input: [0. 0.], Expected Output: 0.0, Predicted Output: 0.5755 (Rounded: 1)
Input: [0. 1.], Expected Output: 1.0, Predicted Output: 0.5754 (Rounded: 1)
Input: [1. 0.], Expected Output: 1.0, Predicted Output: 0.5754 (Rounded: 1)
Input: [1. 1.], Expected Output: 0.0, Predicted Output: 0.2257 (Rounded: 0)


In [ ]:
# 5. Extract optimized weights and biases
print("\nOptimized Weights and Biases:")
for i, layer in enumerate(model.layers):
    weights, biases = layer.get_weights()
    print(f"\nLayer {i+1} ({layer.name}):")
    print(f"  Weights:\n{weights}")
    print(f"  Biases:\n{biases}")


Optimized Weights and Biases:

Layer 1 (dense):
  Weights:
[[0.5183574  0.65111184]
 [0.51804125 0.6517276 ]]
  Biases:
[-0.5181446  -0.65166914]

Layer 2 (dense_1):
  Weights:
[[-1.1466573]
 [-1.4476727]]
  Biases:
[0.30414066]


In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

# 1. Define XOR data
# Input: [0,0], [0,1], [1,0], [1,1]
# Output: 0, 1, 1, 0
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y = np.array([[0], [1], [1], [0]], dtype=np.float32)

print("X (Input):")
print(X)
print("\ny (Output):")
print(y)

# 2. Build the MLP model
# A simple MLP for XOR typically needs at least one hidden layer.
# We'll use a hidden layer with 2 neurons and a ReLU activation,
# and an output layer with 1 neuron and a Sigmoid activation.
model = keras.Sequential([
    # Hidden layer
    keras.layers.Dense(units=2, activation='relu', input_shape=(2,)), # 2 neurons, ReLU activation, input shape is 2 features
    # Output layer
    keras.layers.Dense(units=1, activation='sigmoid') # 1 neuron for binary output, Sigmoid activation
])

# 3. Compile the model
# Optimizer: 'adam' is a good general-purpose optimizer.
# Loss function: 'binary_crossentropy' is suitable for binary classification.
# Metrics: 'accuracy' to monitor performance.
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Display model summary
print("\nModel Summary:")
model.summary()

# 4. Train the model
# We'll train for a sufficient number of epochs to allow the model to learn the XOR pattern.
print("\nTraining the model...")
history = model.fit(X, y, epochs=1000, verbose=0) # verbose=0 to suppress epoch-by-epoch output

print("Training finished.")

# Evaluate the model
loss, accuracy = model.evaluate(X, y, verbose=0)
print(f"\nModel Evaluation:")
print(f"Loss: {loss:.4f}")
print(f"Accuracy: {accuracy:.4f}")

# Make predictions
print("\nPredictions on XOR inputs:")
predictions = model.predict(X)
for i in range(len(X)):
    print(f"Input: {X[i]}, Expected Output: {y[i][0]}, Predicted Output: {predictions[i][0]:.4f} (Rounded: {round(predictions[i][0])})")

# 5. Extract optimized weights and biases
print("\nOptimized Weights and Biases:")
for i, layer in enumerate(model.layers):
    weights, biases = layer.get_weights()
    print(f"\nLayer {i+1} ({layer.name}):")
    print(f"  Weights:\n{weights}")
    print(f"  Biases:\n{biases}")

X (Input):
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]

y (Output):
[[0.]
 [1.]
 [1.]
 [0.]]

Model Summary:


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)


Training the model...
Training finished.

Model Evaluation:
Loss: 0.5069
Accuracy: 0.7500

Predictions on XOR inputs:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
Input: [0. 0.], Expected Output: 0.0, Predicted Output: 0.3785 (Rounded: 0)
Input: [0. 1.], Expected Output: 1.0, Predicted Output: 0.9008 (Rounded: 1)
Input: [1. 0.], Expected Output: 1.0, Predicted Output: 0.3785 (Rounded: 0)
Input: [1. 1.], Expected Output: 0.0, Predicted Output: 0.3787 (Rounded: 0)

Optimized Weights and Biases:

Layer 1 (dense):
  Weights:
[[-0.07738602 -1.1933011 ]
 [-0.09386194  1.1939737 ]]
  Biases:
[ 0.         -0.00037959]

Layer 2 (dense_1):
  Weights:
[[-0.5832497]
 [ 2.2640784]]
  Biases:
[-0.49571183]
